version: '3.4'

services:
  asp.net-core-shceduler-swagger-unittest-:
    image: ${DOCKER_REGISTRY-}asp
    build:
      context: .
      dockerfile: asp.net-core-shceduler-swagger-unittest-/Dockerfile
